version: "3"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  my-hadoop-master:
    image: blitzal/hadoop
    networks:
      - "mynetwork"
    ports:
      - "7788:8080"
  slave1:
    image: blitzal/hadoop
    networks:
      - "mynetwork"
  slave2:
    image: blitzal/hadoop
    networks:
      - "mynetwork"
networks:
  mynetwork:
